-- FACE V2.5 data and commerce foundation
-- Covers member activity, structured daily awareness results, content reading,
-- payment ownership, and durable product entitlements.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Payment orders (server managed)
-- ---------------------------------------------------------------------------

create table if not exists public.payment_orders (
  id uuid primary key default gen_random_uuid(),
  merchant_trade_no varchar(20) not null unique,
  product_code text not null,
  amount integer not null check (amount > 0),
  currency char(3) not null default 'TWD',
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'failed', 'cancelled', 'refunded')),
  payment_provider text not null default 'ecpay',
  payment_environment text not null default 'stage'
    check (payment_environment in ('stage', 'production')),
  ecpay_trade_no text,
  payment_type text,
  provider_payment_date text,
  paid_at timestamptz,
  callback_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.payment_orders
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists customer_email text,
  add column if not exists face_code text,
  add column if not exists payment_provider text not null default 'ecpay',
  add column if not exists payment_environment text not null default 'stage',
  add column if not exists ecpay_trade_no text,
  add column if not exists payment_type text,
  add column if not exists provider_payment_date text;

create index if not exists payment_orders_user_created_idx
  on public.payment_orders (user_id, created_at desc);
create index if not exists payment_orders_status_created_idx
  on public.payment_orders (status, created_at desc);

alter table public.payment_orders enable row level security;

-- Orders contain provider callbacks and remain server-only. Users consume the
-- safer entitlement record instead of reading order payloads through Data API.
revoke all on table public.payment_orders from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Product entitlements (the source of truth for paid status)
-- ---------------------------------------------------------------------------

create table if not exists public.member_entitlements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_code text not null,
  status text not null default 'active'
    check (status in ('active', 'revoked', 'expired')),
  payment_order_id uuid unique references public.payment_orders(id) on delete set null,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_code)
);

create index if not exists member_entitlements_user_status_idx
  on public.member_entitlements (user_id, status);

alter table public.member_entitlements enable row level security;

drop policy if exists "Members can read own entitlements" on public.member_entitlements;
create policy "Members can read own entitlements"
  on public.member_entitlements
  for select
  to authenticated
  using (auth.uid() = user_id);

revoke all on table public.member_entitlements from anon, authenticated;
grant select on table public.member_entitlements to authenticated;

-- ---------------------------------------------------------------------------
-- Sign-in and session activity
-- ---------------------------------------------------------------------------

create table if not exists public.member_activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null
    check (event_type in ('signed_in', 'signed_out', 'session_restored')),
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists member_activity_events_user_time_idx
  on public.member_activity_events (user_id, occurred_at desc);

alter table public.member_activity_events enable row level security;

drop policy if exists "Members can insert own activity" on public.member_activity_events;
create policy "Members can insert own activity"
  on public.member_activity_events
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Members can read own activity" on public.member_activity_events;
create policy "Members can read own activity"
  on public.member_activity_events
  for select
  to authenticated
  using (auth.uid() = user_id);

revoke all on table public.member_activity_events from anon, authenticated;
grant select, insert on table public.member_activity_events to authenticated;
grant usage, select on sequence public.member_activity_events_id_seq to authenticated;

-- ---------------------------------------------------------------------------
-- Public and member content reading progress
-- ---------------------------------------------------------------------------

create table if not exists public.content_reading_progress (
  id uuid primary key default gen_random_uuid(),
  content_id text not null,
  content_slug text not null,
  access_mode text not null
    check (access_mode in ('public', 'login_required', 'paid')),
  user_id uuid references auth.users(id) on delete cascade,
  anonymous_visitor_id uuid,
  view_count integer not null default 1 check (view_count > 0),
  max_progress smallint not null default 0 check (max_progress between 0 and 100),
  first_viewed_at timestamptz not null default now(),
  last_viewed_at timestamptz not null default now(),
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  check (user_id is not null or anonymous_visitor_id is not null)
);

create unique index if not exists content_reading_progress_member_unique
  on public.content_reading_progress (user_id, content_id)
  where user_id is not null;
create unique index if not exists content_reading_progress_guest_unique
  on public.content_reading_progress (anonymous_visitor_id, content_id)
  where user_id is null and anonymous_visitor_id is not null;
create index if not exists content_reading_progress_content_time_idx
  on public.content_reading_progress (content_id, last_viewed_at desc);

alter table public.content_reading_progress enable row level security;

drop policy if exists "Members can read own content progress" on public.content_reading_progress;
create policy "Members can read own content progress"
  on public.content_reading_progress
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Writes are intentionally server-only so anonymous IDs, view counts and
-- completion status cannot be forged through the public Data API.
revoke all on table public.content_reading_progress from anon, authenticated;
grant select on table public.content_reading_progress to authenticated;

-- ---------------------------------------------------------------------------
-- Structured FACE Daily results
-- ---------------------------------------------------------------------------

alter table public.awareness_diary_entries
  add column if not exists face_code text,
  add column if not exists assessment_version text,
  add column if not exists result jsonb,
  add column if not exists completed_at timestamptz;

-- Preserve existing records while separating raw answers from generated result.
update public.awareness_diary_entries
set result = answers -> '_result',
    answers = answers - '_result',
    completed_at = coalesce(completed_at, updated_at)
where result is null
  and jsonb_typeof(answers) = 'object'
  and answers ? '_result';

create index if not exists awareness_diary_entries_user_completed_idx
  on public.awareness_diary_entries (user_id, completed_at desc);

comment on table public.member_entitlements is
  'FACE V2.5 source of truth for paid product access.';
comment on table public.member_activity_events is
  'FACE V2.5 member sign-in, sign-out, and restored-session events.';
comment on table public.content_reading_progress is
  'FACE V2.5 anonymous and member content reading progress.';
