create extension if not exists pgcrypto;

create table public.assessment_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  anonymous_visitor_id uuid not null,
  assessment_version text not null check (char_length(assessment_version) between 1 and 100),
  assessment_type text not null default 'baseline'
    check (assessment_type in ('baseline', 'daily')),
  question_count smallint not null check (question_count between 1 and 200),
  face_code text check (face_code ~ '^[AP][RI][LT][CD]$'),
  focus_score smallint check (focus_score between -100 and 100),
  analysis_score smallint check (analysis_score between -100 and 100),
  cycle_score smallint check (cycle_score between -100 and 100),
  exposure_score smallint check (exposure_score between -100 and 100),
  scores jsonb check (scores is null or jsonb_typeof(scores) = 'object'),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  result_viewed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint assessment_runs_completion_shape check (
    (completed_at is null and face_code is null and scores is null)
    or
    (completed_at is not null and face_code is not null and scores is not null)
  )
);

create index assessment_runs_user_completed_idx
  on public.assessment_runs (user_id, completed_at desc);

create index assessment_runs_visitor_idx
  on public.assessment_runs (anonymous_visitor_id, started_at desc);

create table public.assessment_answers (
  id bigint generated by default as identity primary key,
  assessment_run_id uuid not null references public.assessment_runs (id) on delete cascade,
  question_code text not null check (char_length(question_code) between 1 and 100),
  selected_option text not null check (selected_option in ('A', 'B')),
  dimension text not null check (dimension in ('FOCUS', 'ANALYSIS', 'CYCLE', 'EXPOSURE')),
  score_value smallint not null check (score_value between 0 and 100),
  answered_at timestamptz not null default now(),
  unique (assessment_run_id, question_code)
);

create index assessment_answers_run_idx
  on public.assessment_answers (assessment_run_id);

alter table public.assessment_runs enable row level security;
alter table public.assessment_answers enable row level security;

create policy "Users can read their own assessment runs"
  on public.assessment_runs
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own assessment runs"
  on public.assessment_runs
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own assessment runs"
  on public.assessment_runs
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own incomplete assessment runs"
  on public.assessment_runs
  for delete
  to authenticated
  using ((select auth.uid()) = user_id and completed_at is null);

create policy "Users can read answers for their own assessment runs"
  on public.assessment_answers
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.assessment_runs runs
      where runs.id = assessment_answers.assessment_run_id
        and runs.user_id = (select auth.uid())
    )
  );

create policy "Users can insert answers for their own incomplete runs"
  on public.assessment_answers
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.assessment_runs runs
      where runs.id = assessment_answers.assessment_run_id
        and runs.user_id = (select auth.uid())
        and runs.completed_at is null
    )
  );

create or replace function public.complete_assessment(
  p_run_id uuid,
  p_face_code text,
  p_scores jsonb,
  p_answers jsonb
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  target_run public.assessment_runs%rowtype;
  supplied_answer_count integer;
  unique_question_count integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required';
  end if;

  select *
  into target_run
  from public.assessment_runs
  where id = p_run_id
  for update;

  if not found or target_run.user_id <> auth.uid() then
    raise exception 'Assessment run not found';
  end if;

  -- A retry after a lost network response is safe and does not create duplicates.
  if target_run.completed_at is not null then
    return target_run.id;
  end if;

  if p_face_code !~ '^[AP][RI][LT][CD]$' then
    raise exception 'Invalid FACE code';
  end if;

  if jsonb_typeof(p_scores) <> 'object' then
    raise exception 'Scores must be a JSON object';
  end if;

  if not (p_scores ?& array['A', 'P', 'R', 'I', 'L', 'T', 'C', 'D'])
    or jsonb_typeof(p_scores -> 'A') <> 'number'
    or jsonb_typeof(p_scores -> 'P') <> 'number'
    or jsonb_typeof(p_scores -> 'R') <> 'number'
    or jsonb_typeof(p_scores -> 'I') <> 'number'
    or jsonb_typeof(p_scores -> 'L') <> 'number'
    or jsonb_typeof(p_scores -> 'T') <> 'number'
    or jsonb_typeof(p_scores -> 'C') <> 'number'
    or jsonb_typeof(p_scores -> 'D') <> 'number' then
    raise exception 'Scores must contain all eight numeric FACE traits';
  end if;

  if (p_scores ->> 'A')::smallint + (p_scores ->> 'P')::smallint <> 100
    or (p_scores ->> 'R')::smallint + (p_scores ->> 'I')::smallint <> 100
    or (p_scores ->> 'L')::smallint + (p_scores ->> 'T')::smallint <> 100
    or (p_scores ->> 'C')::smallint + (p_scores ->> 'D')::smallint <> 100 then
    raise exception 'Each FACE dimension must total 100';
  end if;

  if jsonb_typeof(p_answers) <> 'array' then
    raise exception 'Answers must be a JSON array';
  end if;

  select count(*), count(distinct answer ->> 'question_code')
  into supplied_answer_count, unique_question_count
  from jsonb_array_elements(p_answers) answer;

  if supplied_answer_count <> target_run.question_count
    or unique_question_count <> target_run.question_count then
    raise exception 'Expected % unique answers, received %',
      target_run.question_count,
      supplied_answer_count;
  end if;

  insert into public.assessment_answers (
    assessment_run_id,
    question_code,
    selected_option,
    dimension,
    score_value,
    answered_at
  )
  select
    target_run.id,
    trim(answer ->> 'question_code'),
    answer ->> 'selected_option',
    answer ->> 'dimension',
    (answer ->> 'score_value')::smallint,
    coalesce((answer ->> 'answered_at')::timestamptz, now())
  from jsonb_array_elements(p_answers) answer;

  update public.assessment_runs
  set
    face_code = p_face_code,
    focus_score = ((p_scores ->> 'A')::smallint - (p_scores ->> 'P')::smallint),
    analysis_score = ((p_scores ->> 'R')::smallint - (p_scores ->> 'I')::smallint),
    cycle_score = ((p_scores ->> 'L')::smallint - (p_scores ->> 'T')::smallint),
    exposure_score = ((p_scores ->> 'C')::smallint - (p_scores ->> 'D')::smallint),
    scores = p_scores,
    completed_at = now()
  where id = target_run.id;

  return target_run.id;
end;
$$;

revoke all on function public.complete_assessment(uuid, text, jsonb, jsonb) from public;
grant execute on function public.complete_assessment(uuid, text, jsonb, jsonb) to authenticated;

revoke all on table public.assessment_runs from anon, authenticated;
revoke all on table public.assessment_answers from anon, authenticated;
revoke all on sequence public.assessment_answers_id_seq from anon, authenticated;

grant select, insert, delete on public.assessment_runs to authenticated;
grant update (result_viewed_at) on public.assessment_runs to authenticated;
grant select on public.assessment_answers to authenticated;
