create table public.research_participants (
  id uuid primary key default gen_random_uuid(),
  email text unique,
  consent_research boolean not null,
  consent_result_email boolean not null default false,
  consent_marketing boolean not null default false,
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint research_participants_email_shape check (
    email is null or email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  ),
  constraint research_participants_email_consent check (
    (not consent_result_email and not consent_marketing) or email is not null
  )
);

create table public.research_submissions (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid references public.research_participants (id) on delete set null,
  external_response_id text not null unique,
  source text not null default 'google_form',
  assessment_version text not null,
  face_code text not null check (face_code ~ '^[AP][RI][LT][CD]$'),
  scores jsonb not null check (jsonb_typeof(scores) = 'object'),
  not_applicable_count smallint not null default 0 check (not_applicable_count between 0 and 16),
  insufficient_data boolean not null default false,
  submitted_at timestamptz not null,
  received_at timestamptz not null default now(),
  result_released_at timestamptz,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object')
);

create index research_submissions_participant_idx
  on public.research_submissions (participant_id, submitted_at desc);

create table public.research_answers (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.research_submissions (id) on delete cascade,
  question_code text not null,
  selected_option text not null check (selected_option in (
    'A', 'B',
    'very_agree', 'somewhat_agree', 'neutral', 'somewhat_disagree', 'very_disagree',
    'very_a', 'somewhat_a', 'balanced', 'somewhat_b', 'very_b',
    'not_applicable'
  )),
  dimension text not null check (dimension in ('FOCUS', 'ANALYSIS', 'CYCLE', 'EXPOSURE')),
  score_value smallint not null check (score_value between 0 and 10),
  unique (submission_id, question_code)
);

create index research_answers_submission_idx
  on public.research_answers (submission_id);

create table public.research_email_deliveries (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.research_participants (id) on delete cascade,
  submission_id uuid references public.research_submissions (id) on delete set null,
  message_type text not null check (message_type in ('result', 'marketing')),
  provider_message_id text,
  sent_at timestamptz,
  failed_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

alter table public.research_participants enable row level security;
alter table public.research_submissions enable row level security;
alter table public.research_answers enable row level security;
alter table public.research_email_deliveries enable row level security;

-- No browser-facing policies are created. Research data is only accessible
-- through trusted server-side functions using the service role.
revoke all on table public.research_participants from anon, authenticated;
revoke all on table public.research_submissions from anon, authenticated;
revoke all on table public.research_answers from anon, authenticated;
revoke all on table public.research_email_deliveries from anon, authenticated;
revoke all on sequence public.research_answers_id_seq from anon, authenticated;
